# theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
github:
  is_project_page: false
name: jayanthyetukuri's site
title: null

# title: [The title of your site]
# description: [A short description of your site's purpose]
