# theme: jekyll-theme-minimal
# remote_theme: pmarsceill/just-the-docs
# github:
#   is_project_page: false
# name: jayanthyetukuri's site
# title: null

# title: [The title of your site]
# description: [A short description of your site's purpose]

# https://kutaybs.com/gh-pages-template/setup
# https://pmarsceill.github.io/just-the-docs/docs/configuration/
# https://github.com/wiseodd/wiseodd.github.io


theme: jekyll-theme-minimal
title: Home
description: 
show_downloads: False
google_analytics: False
# navigation:
#   - title: Home
#     url: /
#   - title: About
#     url: about
